
services:
  db:
    image: pgvector/pgvector:pg16  # Imagem com Postgres 16 e pgvector
    container_name: go-rag-db-container
    environment:
      - POSTGRES_USER=goku
      - POSTGRES_PASSWORD=kamehameha
      - POSTGRES_DB=go-rag-db
    ports:
      - "5433:5432" # Porta 5433 do host mapeado para porta 5432 do container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    container_name: go-backend-container
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://goku:kamehameha@db:5432/go-rag-db?sslmode=disable
    ports:
      - "8080:8080"
    # Monta o .env local (se existir) dentro do container para o godotenv carregar
    volumes:
      - ./go-backend/.env:/app/.env:ro
      # (Opcional) Compartilha suas credenciais/profiles AWS locais com o container
      - ~/.aws:/root/.aws:ro

volumes:
  postgres_data: